strpbrk_s: Remove unused variable len
Fixes
error: variable 'len' set but not used [-Werror,-Wunused-but-set-variable]

Signed-off-by: Khem Raj <raj.khem@gmail.com>