fix AX_COMPILER_FLAGS probes, and sources
gcc 4.2 fails with -Wmissing-format-attribute in sprintf
probe for -Wl,--as-needed -Wl,-z,relro -Wl,-z,now LDFLAGS

fixed errors (mostly with gcc-4.3 -ansi):
str/sprintf_s.c:145: error: function might be possible candidate for 'printf' format attribute
declaration of 'index' shadows a global declaration
switch missing default case
redundant redeclaration of '_towcase', *time_s, strnlen
extwchar/wcsfc_s.c:289: error: logical '&&' with non-zero constant will always evaluate as true
inlining failed in call to 'handle_error': call is unlikely and code size would grow