cxx !c99 -Werror strictness
warnings being treated as errors.
error: suggest a space before ';' or explicit braces around empty body in 'for' statement
disable -Werror then.

worse is that older g++ (4.3) do not permit
pragma gcc diagnostic inside functions at all.
so we add HAVE_CXX to our HAVE_C99 for this.