fix msys2 deps with gcc-9 update
looking for conflicting packages...
:: mingw-w64-x86_64-pdcurses and mingw-w64-x86_64-ncurses are in conflict. Remove mingw-w64-x86_64-ncurses? [Y/n]
:: mingw-w64-x86_64-pdcurses and mingw-w64-x86_64-termcap are in conflict. Remove mingw-w64-x86_64-termcap? [Y/n]
error: failed to prepare transaction (could not satisfy dependencies)