Define _GNU_SOURCE when needed
Define _GNU_SOURCE to fix build with musl otherwise we'll got the
following build failures due to localtime_r, strnlen, gmtime_r and
asctime_r being undefined:

os/localtime_s.c:124:12: error: implicit declaration of function 'localtime_r'; did you mean 'localtime_s'? [-Werror=implicit-function-declaration]
     dest = localtime_r(timer, dest);
            ^~~~~~~~~~~

io/gets_s.c:144:32: error: implicit declaration of function 'strnlen'; did you mean 'strlen'? [-Werror=implicit-function-declaration]
         rsize_t len = (rsize_t)strnlen(dest, dmax);
                                ^~~~~~~
                                strlen

An other option would be to define AC_GNU_SOURCE in the configure.ac but
it seems that there is some handling of _GNU_SOURCE in
safeclib_private.h

Fixes:
 - http://autobuild.buildroot.net/results/31a4b647ec0dcd9f517f313ec6c7c8f56da1ee47

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>