FreeBSD 11 already has timingsafe_memcmp
We cannot check our probes, because our header is public.
And we don't want to check OS versions neither.
So always include and link our versions.

test_timingsafe_memcmp.c:(.text+0x3a): undefined reference to _timingsafe_memcmp_chk